export const PARKING_LIST_REQUEST = 'PARKING_LIST_REQUEST';
export const PARKING_LIST_SUCCESS='PARKING_LIST_SUCCESS';
export const PARKING_LIST_FAIL='PARKING_LIST_FAIL';


export const PARKING_DELETED="PARKING_DELETED";
export const PARKING_ADDED="PARKING_ADDED"; 



export const PARKING_ADMIN_LIST_REQUEST='PARKING_ADMIN_LIST_REQUEST';
export const PARKING_ADMIN_LIST_SUCCESS="PARKING_ADMIN_LIST_SUCCESS";
export const PARKING_ADMIN_LIST_FAIL="PARKING_ADMIN_LIST_FAIL";
export const PARKING_ADMIN_DELETED="PARKING_ADMIN_DELETED";
export const PARKING_ADMIN_ADDED="PARKING_ADMIN_ADDED";

export const PARKING_DETAILS_SUCCESS="PARKING_DETAILS_SUCCESS"
export const PARKING_DETAILS_FAILED="PARKING_DETAILS_FAILED"