export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LIST_SUCCESS="USERS_LIST_SUCCESS";
export const USER_ADDED_SUCCESS="USER_ADDED_SUCCESS";
export const USER_DELETED="USER_DELETED";
export const USER_ADDED_FAIL="USER_ADDED_FAIL";

export const USER_LIST_UPDATE_SUCCESS="USER_LIST_UPDATE_SUCCESS";
export const USER_LIST_UPDATE_FAIL="USER_LIST_UPDATE_FAIL";


export const RESPONSABLES_LIST_SUCCESS="RESPONSABLES_LIST_SUCCESS"